const products = [
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
  {
    img: "https://source.unsplash.com/user/c_v_r",
    nombre: "Una semilla (una sola)",
    caracteristica: ["toxica", "matagatos"],
    precio: 25030,
  },
];

export { products };
