export const GET_ARRAY_VIVERO = 'GET_ARRAY_VIVERO';
export const GET_ARRAY_HUERTA = 'GET_ARRAY_HUERTA';
export const GET_ARRAY_NOTIFICACIONES = 'GET_ARRAY_NOTIFICACIONES'
export const GET_ARRAY_CARRITO = 'GET_ARRAY_CARRITO'